### ISSUE TITLE
Got error when training ssd300MobileNet with imagenet 

### ISSUE THREAD

**Issue by hungbui-io** [tanakataiki/ssd_kerasV2#15]
Hi @tanakataiki ,
Thanks a lot for such a great work!
I am trying to train your ssd300MobileNet model with ImageNet dataset and got the following error:
> ValueError: Error when checking target: expected predictions to have 3 dimensions, but got array with shape (32, 1000)

With 32 is the batch size and 1000 is number of classes.
Do you have idea how to fix this issue?  Is there any chance of missing Flatten layers before predictions layer (or after softmax)?
Best,
Hung

**Comment by tomsblueskeye** [comment]
How did you solve this issue?
