### ISSUE TITLE
Codes for generating the prior_boxes

### ISSUE THREAD

**Issue by wandonye** [tanakataiki/ssd_kerasV2#19]
It would be great to explain how the prior_boxes are generated or share the codes.

As Issue #5 mentioned, there is a need for modifying these boxes. For example, when you have images with different sizes, or the object you want to detect has a particular aspect ratio so you want to restrict to certain prior_boxes.

Also, from the pkl files for prior boxes, I don't see what the last four columns are used for.

**Comment by wandonye** [comment]
[This article](https://medium.com/@smallfishbigsea/understand-ssd-and-implement-your-own-caa3232cd6ad) is helpful. 
But it may not consistent with the representation of boxes used here in this repo.

**Comment by wandonye** [comment]
The last four columns of the table from the pkl file are variances. Looking into the model files, I found the `variances` parameter in PriorBox is always `variances=[0.1, 0.1, 0.2, 0.2]`. So the variances from the pkl file were not used.

First 4 columns seem to be (min_x,min_y, max_x, max_y).

Hopefully the information here is enough for anyone who wants to create prior boxes themselves

**Comment by UndeadBlow** [comment]
@wandonye Did you succeed with modification of that code for this pipeline? Its generates much more priors that needed.
