### ISSUE TITLE
voc_2007.pkl file not found

### ISSUE THREAD

**Issue by BalajiB197** [tanakataiki/ssd_kerasV2#2]
Can you help me with this file?

**Comment by tanakataiki** [comment]
you can make voc_2007.pkl with in Pascal VOC kit by using below https://github.com/tanakataiki/ssd_kerasV2/blob/master/get_data_from_XML.py

**Comment by hudengjunai** [comment]
> you can make voc_2007.pkl with in Pascal VOC kit by using below https://github.com/tanakataiki/ssd_kerasV2/blob/master/get_data_from_XML.py

Can you reload this file please? I did not find the pickle label file generate python scripts

**Comment by abhi-kumar** [comment]
You may find that file here - https://github.com/rykov8/ssd_keras/blob/master/PASCAL_VOC/get_data_from_XML.py
