### ISSUE TITLE
BatchNormalization axis is probably incorrect.

### ISSUE THREAD

**Issue by wandonye** [tanakataiki/ssd_kerasV2#20]
In the MobileNet based models, only inside the function `_depthwise_conv_block`, you have

```
channel_axis = 1 if K.image_data_format() == 'channels_first' else -1
```

For all the rest functions, you used

```
channel_axis = 1
```

As a result, a few BatchNormalization layer has been renormalizing along the wrong direction. This potentially explains the low accuracy problems which others reported on SSD MobileNet

**Comment by tanakataiki** [comment]
tensor flow backend is channel last so I use axis=-1

**Comment by wandonye** [comment]
-1 is the correct axis. But the problem is that in line 47, 70, 78 and 85 of [ssd300MobileNet.py](https://github.com/tanakataiki/ssd_kerasV2/blob/master/model/ssd300MobileNet.py)

you are using 

```
channel_axis = 1
```

You may want to change these lines into 

```
channel_axis = 1 if K.image_data_format() == 'channels_first' else -1
```
