### ISSUE TITLE
Issues for taking different input shapes as an input into network.

### ISSUE THREAD

**Issue by kihyun1118** [tanakataiki/ssd_kerasV2#22]
Hello, tanaka taiki. Thank you for contributing your codes. I have a question that you mentioned for input shapes. As SSD network consists of fully convolutional network, is there any problem for taking rectangular input images as an input? ( assume that we have the corresponding proper GT bounding box to input images having different shapes. 

Thank you!

**Comment by pedromlsreis** [comment]
@kihyun1118 Can you please share how you solved this issue?
