### ISSUE TITLE
l2_normalize() got an unexpected keyword argument 'axis'

### ISSUE THREAD

**Issue by yhxuyou** [tanakataiki/ssd_kerasV2#3]
i have updated keras from 2.1.2 to 2.1.5,when i try to run the videotest_example.py and  occur this error,can u help me to solve this problem。thank u very much！！

**Comment by yhxuyou** [comment]
em.. and why i use your code to run MobileNet(13FPS) is too slower than VGG16(20FPS),and i use GPU is 1080Ti?~~

**Comment by tanakataiki** [comment]
MobileNet doesnt use l2_normalize where does that error occurs? VGG16 use l2 normalize
 and what GPU do you use ?
