### ISSUE TITLE
how to generate prior_boxes

### ISSUE THREAD

**Issue by algila** [tanakataiki/ssd_kerasV2#5]
Hi, may you explain how to generate the prior files ? 
I would train using my own training set

**Comment by tanakataiki** [comment]
U should use get data from xml file to train ur own dataset

**Comment by algila** [comment]
Hi, I used the file  `get_data_from_XML.py`  to generate `voc_2012.pkl` 
How to generate the files you stored in the folder `priorFiles` ?

I need to train MobileNet 256x256 alpha 0,125 (This is the max size of the model tha should work in Google AIY vision kit)

**Comment by algila** [comment]
I see that the file `prior_boxes_ssd300MobileNet.pkl` doesn't work if the input image is 256x256. 
May I kindly ask you to upload in the project folder `priorFiles` also this file  ? 
If it is not too much time consuming may you upload the same file 256x256 related to MobileNetV2 and Featurefused ?
