### ISSUE TITLE
Use alpha parameter in MobileNet

### ISSUE THREAD

**Issue by algila** [tanakataiki/ssd_kerasV2#7]
Hi, I see in the code that the model MobileNet is using alpha parameter =1. Do you have any plan to generalize the model for any alpha defined by the user ?

**Comment by tanakataiki** [comment]
the prittained weight only support alpha=1
so, you have to implement mobilenet by your self and transfer weights to them is the only way I think.

**Comment by algila** [comment]
Hi, in reality MobileNet in keras just support alpha parameter, so the only needed action is to be able to transfer weight from your net with alpha=1 to the net with a different alpha, but do you know how ?
